name: Bluesky Biodiversity Bot

on:
  schedule:
    - cron: '0 */2 * * *' # Every 2 hours
  workflow_dispatch:
    # Allow manual trigger

jobs:
  post-bird:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Cache Puppeteer browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/puppeteer
        key: ${{ runner.os }}-puppeteer-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-puppeteer-
        
    - name: Install dependencies
      run: npm ci
      
    - name: Determine post type
      id: post-type
      run: |
        # Generate random number 1-3: mammals if 1, birds otherwise (2 or 3)
        RANDOM_NUM=$((RANDOM % 3 + 1))
        if [ $RANDOM_NUM -eq 1 ]; then
          echo "POST_TYPE=mammals" >> $GITHUB_OUTPUT
          echo "Running mammals post (random: $RANDOM_NUM)"
        else
          echo "POST_TYPE=birds" >> $GITHUB_OUTPUT
          echo "Running birds post (random: $RANDOM_NUM)"
        fi

    - name: Run Bluesky bot
      env:
        BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
        BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
      run: |
        if [ "${{ steps.post-type.outputs.POST_TYPE }}" = "mammals" ]; then
          npx tsx bluesky-bot.ts --mammals
        else
          npx tsx bluesky-bot.ts
        fi
